# Generated by Django 4.1.7 on 2023-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_text_files', models.FileField(max_length=255, upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),

            ],
        ),
    ]
