# Generated by Django 4.1.7 on 2023-04-04 19:05

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]

