# Generated by Django 4.1.7 on 2023-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0003_auto_20230405_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_text_files',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=' ', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
