# Generated by Django 4.1.7 on 2023-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0005_remove_uploadedfile_file_remove_uploadedfile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
