# Generated by Django 4.1.7 on 2023-04-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0006_uploadedfile_file_uploadedfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name',
        ),
    ]
