# Generated by Django 4.1.7 on 2023-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0007_remove_uploadedfile_file_remove_uploadedfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_1',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_3',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_4',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_5',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_6',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_7',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_8',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_4',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_5',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_6',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_7',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name_8',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=' ', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
