# Generated by Django 4.1.7 on 2023-04-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0008_remove_uploadedfile_file_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_2',
            field=models.FileField(default=' ', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
