# Generated by Django 4.1.7 on 2023-04-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0009_uploadedfile_file_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_2',
        ),
    ]
