# Generated by Django 4.1.7 on 2023-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1stapp', '0010_remove_uploadedfile_file_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
